// The overlay this build carries: null on the open-source tree, the Enterprise
// contract when `ee/` is linked in. `src/ee/index.ts` is generated by
// scripts/ee.mjs and is the only file that may import the overlay.
import type { EnterpriseOverlay } from './overlay.js'
import { overlay } from '../ee/index.js'

export const enterprise: EnterpriseOverlay | null = overlay
