/**
 * Drop-in acceptance-test bundle for ANY repo (greenfield or existing), with no
 * git-provider connection: a set of files an AI (or a human) commits into the
 * product checkout. It carries the verified prototype's contract — the Playwright
 * specs + Gherkin + a Playwright config + a CI workflow that runs them (so they
 * can gate merge via branch protection) + a pre-filled `lyriks.map.json` the user
 * edits to retarget the SAME tests onto an existing app's routes/selectors.
 *
 * Pure functions only.
 */
import type { ProjectExperienceDraft } from './draft';
import { screenPath } from './draft';
import { buildAcceptanceSpec } from './acceptance';
import { generateAcceptanceTests, type TargetMap } from './acceptance-tests';

export interface ScaffoldFile {
	path: string;
	content: string;
}
export interface RepoScaffold {
	files: ScaffoldFile[];
	summary: {
		journeyCount: number;
		criteriaCount: number;
		boundAssertions: number;
		annotatedAssertions: number;
	};
}

const PLAYWRIGHT_CONFIG = `import { defineConfig } from '@playwright/test';

// Generated by Lyriks. Point baseURL at your running app (or set BASE_URL).
export default defineConfig({
  testDir: './tests/acceptance',
  reporter: 'list',
  use: { baseURL: process.env.BASE_URL ?? 'http://localhost:3000' }
});
`;

const CI_WORKFLOW = `name: Acceptance (generated from Lyriks prototype)
# Wire this into branch protection to BLOCK merge on a failing acceptance test.
on:
  pull_request:
  workflow_dispatch:
jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run acceptance tests
        run: npx playwright test --config playwright.config.ts
        env:
          BASE_URL: \${{ vars.ACCEPTANCE_BASE_URL || 'http://localhost:3000' }}
`;

/** A starter TargetMap pre-filled with the prototype's screens + nav labels. */
function starterMap(draft: ProjectExperienceDraft): string {
	const spec = buildAcceptanceSpec(draft);
	const routes: Record<string, string> = {};
	for (const s of draft.screens) routes[s.name?.trim() || s.id] = screenPath(s);
	const selectors: Record<string, string> = {};
	for (const f of spec.features) for (const h of f.hops) selectors[h.viaLabel] = '';
	return JSON.stringify(
		{
			$comment:
				'Retarget the generated acceptance tests onto THIS repo. routes: screen name → real path. selectors: element label → CSS selector (leave "" to keep role+name). observables: state path → how to assert it in the real UI.',
			routes,
			selectors,
			observables: {}
		},
		null,
		2
	);
}

function readme(summary: RepoScaffold['summary']): string {
	return `# Acceptance tests (generated by Lyriks)

These tests are the contract of the **verified Experience prototype**, and they were
generated from journeys that were simulated end-to-end before any code was written.

- \`tests/acceptance/acceptance.spec.ts\`: Playwright E2E (routes + accessible names).
- \`tests/acceptance/acceptance.feature\`: the same contract as Gherkin (BDD/docs).
- \`playwright.config.ts\`: point \`baseURL\` at your app.
- \`.github/workflows/acceptance.yml\`: runs them in CI; add it to branch protection to block merge.
- \`lyriks.map.json\`: **existing projects:** edit this to map prototype screens/labels onto
  your real routes/selectors, then re-generate (no git provider needed).

Coverage of authored scenarios: **${summary.boundAssertions} auto-bound** to real assertions,
**${summary.annotatedAssertions} left as \`// acceptance (bind manually)\`** (internal state with no
observable in the prototype yet, so bind those to a real check).

Run: \`npx playwright test\`.
`;
}

export function generateRepoScaffold(draft: ProjectExperienceDraft, map: TargetMap = {}): RepoScaffold {
	const tests = generateAcceptanceTests(draft, map);
	const summary = {
		journeyCount: tests.journeyCount,
		criteriaCount: tests.criteriaCount,
		boundAssertions: tests.boundAssertions,
		annotatedAssertions: tests.annotatedAssertions
	};
	return {
		files: [
			{ path: 'tests/acceptance/acceptance.spec.ts', content: tests.playwright },
			{ path: 'tests/acceptance/acceptance.feature', content: tests.gherkin + '\n' },
			{ path: 'playwright.config.ts', content: PLAYWRIGHT_CONFIG },
			{ path: '.github/workflows/acceptance.yml', content: CI_WORKFLOW },
			{ path: 'lyriks.map.json', content: starterMap(draft) + '\n' },
			{ path: 'ACCEPTANCE.md', content: readme(summary) }
		],
		summary
	};
}
