/**
 * Offline icon registration — import once for its side effect (root layout).
 *
 * The app references icons by name (`lucide:<name>`); by default `@iconify/svelte`
 * would fetch missing icon data from the public `api.iconify.design` at runtime,
 * which breaks an air-gapped / on-prem install (see
 * docs/deployment/05-architecture-validation.md, finding F1).
 *
 * We register a bundled subset of the lucide set (generated by
 * scripts/build-icon-subset.mjs) and then NEUTRALISE the remote API so that even
 * an unregistered name can never trigger an outbound request — it simply renders
 * empty. Result: every icon the UI uses renders locally, with zero egress.
 */
import { addCollection, addAPIProvider, _api } from '@iconify/svelte';
import lucideOffline from './lucide-offline.json';

addCollection(lucideOffline as Parameters<typeof addCollection>[0]);

// Air-gap guarantee: empty the default API provider AND reject any fetch the
// loader might still attempt. No icon lookup ever reaches the network.
addAPIProvider('', { resources: [] });
_api.setFetch((() => Promise.reject(new Error('iconify: offline, remote API disabled'))) as typeof fetch);
