// Generated by scripts/ee.mjs: the open-source tree carries no Enterprise overlay.
import type { EnterpriseOverlay } from '../enterprise/overlay.js'

export const overlay: EnterpriseOverlay | null = null
