#!/usr/bin/env node
/**
 * Link or unlink the Enterprise overlay into the gateway source.
 *
 *   node scripts/ee.mjs link     copy ee/ -> src/ee/ and point src/ee/index.ts at it
 *   node scripts/ee.mjs unlink   replace src/ee/ with the open-source stub
 *   node scripts/ee.mjs ensure   link when ee/ exists (a private checkout), else stub
 *   node scripts/ee.mjs status   print "linked" or "unlinked"
 *
 * A copy, not a symlink, like the platform's overlay: esbuild, tsx, tsc and
 * vitest then see one ordinary tree. src/ee/ is git-ignored on the private
 * repository and committed as the stub on the public one, so `ensure` is a
 * no-op there. Edit ee/, never src/ee/: `ensure` runs before dev, build,
 * typecheck and test and rewrites the copy every time.
 */
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const OVERLAY = { from: resolve(root, 'ee'), to: resolve(root, 'src/ee') };

const STUB = `// Generated by scripts/ee.mjs: the open-source tree carries no Enterprise overlay.
import type { EnterpriseOverlay } from '../enterprise/overlay.js'

export const overlay: EnterpriseOverlay | null = null
`;
const LINKED = `// Generated by scripts/ee.mjs link: the Enterprise overlay is linked in.
export { overlay } from './register.js'
`;

export function overlayAvailable() {
	return existsSync(join(OVERLAY.from, 'register.ts'));
}

export function overlayLinked() {
	return existsSync(join(OVERLAY.to, 'register.ts'));
}

export function linkOverlay() {
	if (!overlayAvailable()) return false;
	rmSync(OVERLAY.to, { recursive: true, force: true });
	cpSync(OVERLAY.from, OVERLAY.to, { recursive: true });
	writeFileSync(join(OVERLAY.to, 'index.ts'), LINKED);
	return true;
}

export function unlinkOverlay() {
	rmSync(OVERLAY.to, { recursive: true, force: true });
	mkdirSync(OVERLAY.to, { recursive: true });
	writeFileSync(join(OVERLAY.to, 'index.ts'), STUB);
}

/** The tree decides the edition: a checkout with ee/ builds Enterprise, one without builds Community. */
export function ensureOverlay() {
	if (overlayAvailable()) return linkOverlay() ? 'linked' : 'unlinked';
	if (!existsSync(join(OVERLAY.to, 'index.ts'))) unlinkOverlay();
	return 'unlinked';
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const command = process.argv[2];
	if (command === 'link') {
		if (linkOverlay()) console.log('[ee] overlay linked into src/ee');
		else {
			console.error('[ee] no ee/ overlay in this tree');
			process.exit(1);
		}
	} else if (command === 'unlink') {
		unlinkOverlay();
		console.log('[ee] overlay unlinked: open-source tree');
	} else if (command === 'ensure') {
		console.log(`[ee] ${ensureOverlay()}`);
	} else if (command === 'status') {
		console.log(overlayLinked() ? 'linked' : 'unlinked');
	} else {
		console.error('usage: node scripts/ee.mjs link|unlink|ensure|status');
		process.exit(2);
	}
}
