<script lang="ts" module>
	// Register only the grammars we use so the bundle stays lean. Synchronous +
	// SSR-safe (no async highlighter instance).
	import hljs from 'highlight.js/lib/core';
	import yaml from 'highlight.js/lib/languages/yaml';
	import json from 'highlight.js/lib/languages/json';
	hljs.registerLanguage('yaml', yaml);
	hljs.registerLanguage('json', json);
</script>

<script lang="ts">
	interface Props {
		code: string;
		language?: 'yaml' | 'json';
		/** When set, renders a macOS-style editor title bar with this filename. */
		filename?: string;
	}
	let { code, language = 'yaml', filename }: Props = $props();

	// `code` is generated by Lyriks (the compiled contract) — trusted input.
	const html = $derived(hljs.highlight(code, { language }).value);
</script>

<div
	class="lyr-codewrap overflow-hidden rounded-xl border border-white/10 shadow-[inset_0_1px_0_rgba(255,255,255,0.04),0_10px_30px_-15px_rgba(0,0,0,0.8)]"
>
	{#if filename}
		<div class="flex items-center gap-2 border-b border-white/10 bg-white/[0.03] px-3.5 py-2">
			<span class="flex items-center gap-1.5" aria-hidden="true">
				<span class="size-[11px] rounded-full bg-[#ff5f57]"></span>
				<span class="size-[11px] rounded-full bg-[#febc2e]"></span>
				<span class="size-[11px] rounded-full bg-[#28c840]"></span>
			</span>
			<span class="ml-1.5 truncate font-mono text-[11px] text-ink-400">{filename}</span>
			<span
				class="ml-auto rounded bg-white/10 px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-[0.1em] text-ink-300"
				>{language}</span
			>
		</div>
	{/if}
	<pre class="lyr-code overflow-x-auto p-4 font-mono text-[11.5px] leading-[1.7] text-slate-200"><code
			>{@html html}</code
		></pre>
</div>

<style>
	/* Deep editor surface with a faint vertical sheen. */
	.lyr-codewrap {
		background:
			radial-gradient(120% 100% at 0% 0%, rgba(124, 58, 237, 0.08), transparent 60%),
			linear-gradient(180deg, #0c1222 0%, #090d18 100%);
	}

	/* Custom token palette — tuned to the mockup's colored contract. */
	.lyr-code :global(.hljs-attr),
	.lyr-code :global(.hljs-attribute) {
		color: #c4b5fd; /* keys — violet */
		font-weight: 500;
	}
	.lyr-code :global(.hljs-string) {
		color: #6ee7b7; /* strings — emerald */
	}
	.lyr-code :global(.hljs-number) {
		color: #fcd34d; /* numbers — amber */
	}
	.lyr-code :global(.hljs-bullet),
	.lyr-code :global(.hljs-literal),
	.lyr-code :global(.hljs-type) {
		color: #67e8f9; /* lists / literals — cyan */
	}
	.lyr-code :global(.hljs-keyword),
	.lyr-code :global(.hljs-meta) {
		color: #f0abfc; /* keywords — fuchsia */
	}
	.lyr-code :global(.hljs-comment) {
		color: #64748b; /* comments — slate */
		font-style: italic;
	}
</style>
